config/routes.rb
Rails.application.routes.draw do
  get '/login',to: 'sessions#new'
  post    '/login',to: 'sessions#create'
  delete  '/logout',to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    def self.search(search)
        if search
          where('name LIKE ?', "%#{search}%")
        else
          all
        end
      end
      private
end

app/controllers/application_controller.rb
  
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :require_login

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by name: params[:session][:name]
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to users_path
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i(new create)

  def index
    @users = User.page(params[:page]).per(10).search(params[:search])
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register success"
      redirect_to login_path
    else
      flash[:success] = "Register failed"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
  
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      flash[:success] = "Profile updated failed"
      render 'edit'
    end
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
end
  

app/helpers/users_helper.rb
module UsersHelper
    def create_index params_page, index, per_page
        params_page = 1 if params_page.nil?
        (params_page.to_i - 1) * per_page.to_i + index.to_i + 1
      end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.id %></td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>


      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xl-12 text-center">
      <h1 class="title">LOGIN APP</h1>
    </div>
    <div class="col-xl-12 form-group">
      <label for="">Welcome</label>
      <%= link_to current_user.name, user_path(current_user) %>
    </div>
    <h1 class="text-center" style="color: red;">Users list</h1>
<div class="col-md-10 col-lg-offset-1">
  <table class="table text-center" style="border: 2px solid black;">
    <tr class="bg-primary">
      <th class="text-center col-md-1">Index</th>
      <th class="text-center col-md-2">Name</th>
      <th class="text-center col-md-3">Id</th>
      <th class="text-center col-md-3">Show</th>
      <th class="text-center col-md-3">Edit</th>
      <th class="text-center col-md-3">Destroy</th>

    </tr>
      <% @users.each_with_index do |user, index| %>
        <tr class="bg-info">
        <td><%= create_index params[:page], index, 10 %></td>
        <td scope="row"><%= user.name %></td>
        <td scope="row"><%= user.id %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>

<div>
<%= form_tag(users_path,:method => 'get') do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

</div>

  </table>
      <%= paginate @users %>
</div>

  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">Register</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for @user, html:{class:"form-horizontal"} do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name", class: "control-label" %>
          <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "Password", class: "control-label" %>
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Password Confirmation", class: "control-label" %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
        </div>
        <div class="form-group">
          <div class="text-center">
            <%= f.submit "Register", class: "btn btn-info col-lg-12" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left col-lg-6", style="padding-left: 0px ">
        <label>User name: <%= @user.name %></label>
      </div>
      <div class="text-right col-lg-6">
        <%= link_to "Logout", logout_path, method: :delete %>
      </div>
    </div>
    <div class="col-lg-offset-3 col-lg-6">
      <%= link_to "List Users", users_path %>
    </div>
  </div>
</div>